SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20 # 20
ASTEROID_KINDS = 4 # 3
ASTEROID_SPAWN_RATE = 0.5 # seconds # 5
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_ACC = 1.2
ASTEROID_BASE_ROTATE_SPEED = 50 
ASTEROID_ROTATE_SPEED_RANDOM = 5
#ASTEROID_COLLISION_RANDOM = 100 # 1 in N chance per tick

PLAYER_RADIUS = 20 #20
PLAYER_TURN_SPEED = 2 #4
PLAYER_SPEED = 2.3 #5
PLAYER_SHOOT_SPEED = 350 
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_BOMB_COOLDOWN = 0.8
PLAYER_BOMB_COUNT = 2
PLAYER_HEALTH = 10
PLAYER_LIFE = 1
PLAYER_RESPAWN_LAG = 2

SHOT_RADIUS = 3
SHOT_LIFE = 0.9
SHOT_DAMAGE = 10

COLLISION_DP = 20
RESPAWN_BOOM = 99999

Infinite_lives = False
Infinite_bombs = True
Collisions_on = True
Player_collisions_on = True
Draw_on = False
#Bullet_collisions_on = True