SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPLIT_ACC = 1.2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 4
PLAYER_SPEED = 5

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 4.2 # no longer in the hundreds since no more *dt
PLAYER_SHOOT_COOLDOWN = 0.3

Collisions_on = True
Player_collisions_on = False
#Bullet_collisions_on = True